### ISSUE TITLE
using multiple aa databases, ERROR: Two different tasks can't have a common target

### ISSUE THREAD

**Issue by ljcohen** [dib-lab/dammit#126]
Command:
```
(py3.dammit) [ljcohen@r036 bridges]$ dammit annotate /pylon5/bi5fpmp/ljcohen/kfish_trinity/F_notti.trinity_out.Trinity.fasta --busco-group eukaryota \
>      --user-databases /pylon5/bi5fpmp/ljcohen/Fhet_reference_genome/ncbi/protein.fa /pylon5/bi5fpmp/ljcohen/Fhet_reference_genome/evigene/kfish2rae5g.pub.aa /pylon5/bi5fpmp/ljcohen/Fhet_reference_genome/ensembl/Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa \
>      --output-dir /pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit \
>      --n_threads 14
```
Output:
```
/home/ljcohen/miniconda3/envs/py3.dammit/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ljcohen/miniconda3/envs/py3.dammit/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
/home/ljcohen/miniconda3/envs/py3.dammit/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
# dammit
## a tool for easy de novo transcriptome annotation

by Camille Scott

**v1.0rc2**, 2018

## submodule: annotate
### Database Check
#### Info
* Database Directory: /pylon5/bi5fpmp/ljcohen/dammit
* Doit Database: /pylon5/bi5fpmp/ljcohen/dammit/databases.doit.db


*All database tasks up-to-date.*

### Annotation
#### Info
* Doit Database: /pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/annotate.doit.db
* Input Transcriptome: /pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta


Some tasks out of date!


Out-of-date tasks:
* BUSCO-eukaryota
* TransDecoder.LongOrfs
* TransDecoder.Predict
* annotate:fasta
* cmscan:Rfam
* gff3:/pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta.x.Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa.crbl.csv
* gff3:/pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta.x.kfish2rae5g.pub.aa.crbl.csv
* gff3:/pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta.x.protein.fa.crbl.csv
* gff3:OrthoDB
* gff3:Pfam-A
* gff3:Rfam
* gff3:merge-all
* hmmscan:Pfam-A
* hmmscan:Pfam-A:remap
* lastal:OrthoDB
* lastal:best-hits:OrthoDB
* rename-transcriptome
* transcriptome-stats
* user-database:Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa-shmlast-fit_and_filter_crbl_hits
* user-database:Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa-shmlast-lastal:.F_notti.trinity_out.Trinity.fasta.pep.x.Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa.maf
* user-database:Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa-shmlast-lastal:.Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa.x.F_notti.trinity_out.Trinity.fasta.pep.maf
* user-database:Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa-shmlast-lastdb:.F_notti.trinity_out.Trinity.fasta.pep
* user-database:Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa-shmlast-lastdb:.Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa
* user-database:Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa-shmlast-rename:/pylon5/bi5fpmp/ljcohen/Fhet_reference_genome/ensembl/Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa
* user-database:Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa-shmlast-rename:/pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta
* user-database:Fundulus_heteroclitus.Fundulus_heteroclitus-3.0.2.pep.all.fa-shmlast-translate:.F_notti.trinity_out.Trinity.fasta
* user-database:kfish2rae5g.pub.aa-shmlast-fit_and_filter_crbl_hits
* user-database:kfish2rae5g.pub.aa-shmlast-lastal:.F_notti.trinity_out.Trinity.fasta.pep.x.kfish2rae5g.pub.aa.maf
* user-database:kfish2rae5g.pub.aa-shmlast-lastal:.kfish2rae5g.pub.aa.x.F_notti.trinity_out.Trinity.fasta.pep.maf
* user-database:kfish2rae5g.pub.aa-shmlast-lastdb:.F_notti.trinity_out.Trinity.fasta.pep
* user-database:kfish2rae5g.pub.aa-shmlast-lastdb:.kfish2rae5g.pub.aa
* user-database:kfish2rae5g.pub.aa-shmlast-rename:/pylon5/bi5fpmp/ljcohen/Fhet_reference_genome/evigene/kfish2rae5g.pub.aa
* user-database:kfish2rae5g.pub.aa-shmlast-rename:/pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta
* user-database:kfish2rae5g.pub.aa-shmlast-translate:.F_notti.trinity_out.Trinity.fasta
* user-database:protein.fa-shmlast-fit_and_filter_crbl_hits
* user-database:protein.fa-shmlast-lastal:.F_notti.trinity_out.Trinity.fasta.pep.x.protein.fa.maf
* user-database:protein.fa-shmlast-lastal:.protein.fa.x.F_notti.trinity_out.Trinity.fasta.pep.maf
* user-database:protein.fa-shmlast-lastdb:.F_notti.trinity_out.Trinity.fasta.pep
* user-database:protein.fa-shmlast-lastdb:.protein.fa
* user-database:protein.fa-shmlast-rename:/pylon5/bi5fpmp/ljcohen/Fhet_reference_genome/ncbi/protein.fa
* user-database:protein.fa-shmlast-rename:/pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta
* user-database:protein.fa-shmlast-translate:.F_notti.trinity_out.Trinity.fasta

#### Run Tasks
ERROR: Two different tasks can't have a common target.'.F_notti.trinity_out.Trinity.fasta' is a target for user-database:kfish2rae5g.pub.aa-shmlast-rename:/pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta and user-database:protein.fa-shmlast-rename:/pylon5/bi5fpmp/ljcohen/kfish_dammit/F_notti.dammit/F_notti.trinity_out.Trinity.fasta.
(py3.dammit) [ljcohen@r036 bridges]$ srun: Force Terminated job 4629042
srun: Job step aborted: Waiting up to 302 seconds for job step to finish.
timed out waiting for input: auto-logout
srun: error: r036: task 0: Exited with exit code 3
```

**Comment by camillescott** [comment]
Resolved!

**Comment by ericavt** [comment]
Hi, Camille.
Thanks for putting together a great solution to annotating transcriptomes!
I've just hit the same 'Two different tasks can't have a common target' error when trying to specify 3 user databases. Was there a solution to this? Thanks!

Command:
`dammit annotate TrinitySI18_1_cdh99.fasta --database-dir /xxxx/project/xxxx/bin/AnnotationDBs --full --user-databases Danio_rerio.GRCz11.pep.all.fa Oreochromis_niloticus.Orenil1.0.pep.all.fa Labrus_bergylta.BallGen_V1.pep.all.fa --busco-group vertebrata --n_threads 16`

Output (Just the end, as I also got a lot of Disk quota exceeded errors!)
`Arguments: ()
--- Logging error ---
Traceback (most recent call last):
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/logging/__init__.py", line 998, in emit
    self.flush()
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/logging/__init__.py", line 978, in flush
    self.stream.flush()
OSError: [Errno 122] Disk quota exceeded
Call stack:
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/bin/dammit", line 9, in <module>
    sys.exit(app.DammitApp(arg_src=sys.argv[1:]).run())
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/site-packages/dammit/app.py", line 45, in run
    return self.args.func()
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/site-packages/dammit/app.py", line 330, in handle_annotate
    return annotate.run_annotation(annotate_handler)
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/site-packages/dammit/annotate.py", line 100, in run_annotation
    return handler.run()
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/site-packages/dammit/handler.py", line 224, in run
    return runner.run(doit_args)
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/site-packages/doit/cmd_base.py", line 389, in execute
    self, params, args)
  File "/nesi/project/nesi00431/bin/miniconda_envs/dammit/lib/python3.6/site-packages/dammit/handler.py", line 195, in load_tasks
    self.logger.debug('loading {0} tasks'.format(len(self.tasks)))
Message: 'loading 45 tasks'
Arguments: ()
ERROR: Two different tasks can't have a common target.'.TrinitySI18_1_cdh99.fasta' is a target for user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-rename:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta and user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-rename:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta.
# dammit
## a tool for easy de novo transcriptome annotation

by Camille Scott

**v1.0rc2**, 2018

## submodule: annotate
### Database Check
#### Info
* Database Directory: /nesi/project/nesi00431/bin/AnnotationDBs
* Doit Database: /nesi/project/nesi00431/bin/AnnotationDBs/databases.doit.db


*All database tasks up-to-date.*

### Annotation
#### Info
* Doit Database: /scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/annotate.doit.db
* Input Transcriptome: /scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta


Some tasks out of date!


Out-of-date tasks:
* BUSCO-vertebrata
* TransDecoder.LongOrfs
* TransDecoder.Predict
* annotate:fasta
* cmscan:Rfam
* gff3:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta.x.Danio_rerio.GRCz11.pep.all.fa.crbl.csv
* gff3:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta.x.Labrus_bergylta.BallGen_V1.pep.all.fa.crbl.csv
* gff3:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta.x.Oreochromis_niloticus.Orenil1.0.pep.all.fa.crbl.csv
* gff3:OrthoDB
* gff3:Pfam-A
* gff3:Rfam
* gff3:merge-all
* gff3:uniref90
* hmmscan:Pfam-A
* hmmscan:Pfam-A:remap
* lastal:OrthoDB
* lastal:best-hits:OrthoDB
* lastal:best-hits:uniref90
* lastal:uniref90
* rename-transcriptome
* transcriptome-stats
* user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-fit_and_filter_crbl_hits
* user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-lastal:.Danio_rerio.GRCz11.pep.all.fa.x.TrinitySI18_1_cdh99.fasta.pep.maf
* user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-lastal:.TrinitySI18_1_cdh99.fasta.pep.x.Danio_rerio.GRCz11.pep.all.fa.maf
* user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-lastdb:.Danio_rerio.GRCz11.pep.all.fa
* user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-lastdb:.TrinitySI18_1_cdh99.fasta.pep
* user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-rename:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/Danio_rerio.GRCz11.pep.all.fa
* user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-rename:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta
* user-database:Danio_rerio.GRCz11.pep.all.fa-shmlast-translate:.TrinitySI18_1_cdh99.fasta
* user-database:Labrus_bergylta.BallGen_V1.pep.all.fa-shmlast-fit_and_filter_crbl_hits
* user-database:Labrus_bergylta.BallGen_V1.pep.all.fa-shmlast-lastal:.Labrus_bergylta.BallGen_V1.pep.all.fa.x.TrinitySI18_1_cdh99.fasta.pep.maf
* user-database:Labrus_bergylta.BallGen_V1.pep.all.fa-shmlast-lastal:.TrinitySI18_1_cdh99.fasta.pep.x.Labrus_bergylta.BallGen_V1.pep.all.fa.maf
* user-database:Labrus_bergylta.BallGen_V1.pep.all.fa-shmlast-lastdb:.Labrus_bergylta.BallGen_V1.pep.all.fa
* user-database:Labrus_bergylta.BallGen_V1.pep.all.fa-shmlast-lastdb:.TrinitySI18_1_cdh99.fasta.pep
* user-database:Labrus_bergylta.BallGen_V1.pep.all.fa-shmlast-rename:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/Labrus_bergylta.BallGen_V1.pep.all.fa
* user-database:Labrus_bergylta.BallGen_V1.pep.all.fa-shmlast-rename:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta
* user-database:Labrus_bergylta.BallGen_V1.pep.all.fa-shmlast-translate:.TrinitySI18_1_cdh99.fasta
* user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-fit_and_filter_crbl_hits
* user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-lastal:.Oreochromis_niloticus.Orenil1.0.pep.all.fa.x.TrinitySI18_1_cdh99.fasta.pep.maf
* user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-lastal:.TrinitySI18_1_cdh99.fasta.pep.x.Oreochromis_niloticus.Orenil1.0.pep.all.fa.maf
* user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-lastdb:.Oreochromis_niloticus.Orenil1.0.pep.all.fa
* user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-lastdb:.TrinitySI18_1_cdh99.fasta.pep
* user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-rename:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/Oreochromis_niloticus.Orenil1.0.pep.all.fa
* user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-rename:/scale_wlg_nobackup/filesets/nobackup/nesi00427/Annotation/TrinitySI18_1_cdh99.fasta.dammit/TrinitySI18_1_cdh99.fasta
* user-database:Oreochromis_niloticus.Orenil1.0.pep.all.fa-shmlast-translate:.TrinitySI18_1_cdh99.fasta

#### Run Tasks
(END)`
