### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by johnsolk** [dib-lab/dammit#138]
Is there a DOI for dammit? 

Also, previous citations pointed to http://www.camillescott.org/dammit, which no longer exists.

**Comment by ljcohen** [comment]
Could you put a link on your [old page](http://www.camillescott.org/dammit) that points to the [new page](http://dib-lab.github.io/dammit/)? Because there are likely many existing citations that included the old page. :)

**Comment by camillescott** [comment]
Done!
